### ISSUE TITLE
How can I set mergin URL variable 

### ISSUE THREAD

**Issue by tuankhanh78** [MerginMaps/mergin-media-sync#23]
Hi,

On this example 👍 How can I set up my mergin URL variable ?
Do I have to add MERGIB__URL="https://mergin.example.com" ?

docker run -it \
  -v /tmp/mediasync:/data \
  --name mergin-media-sync \
  -e MERGIN__USERNAME=john \
  -e MERGIN__PASSWORD=myStrongPassword \
  -e MERGIN__PROJECT_NAME=john/my_project \
  -e LOCAL__DEST=/data \
  -e OPERATION_MODE=move \
  -e REFERENCES = "[{file='my_survey.gpkg', table='my_table', local_path_column='col_with_path', driver_path_column='col_with_ext_url'}]" \
  lutraconsulting/mergin-media-sync python3 media_sync_daemon.py

Regards

**Comment by PeterPetrik** [comment]
yes 

```
docker run -it 
-v /tmp/mediasync:/data 
--name mergin-media-sync 
-e MERGIN__USERNAME=john
-e MERGIN__URL=myURL
-e MERGIN__PASSWORD=myStrongPassword 
-e MERGIN__PROJECT_NAME=john/my_project 
-e LOCAL__DEST=/data 
-e OPERATION_MODE=move 
-e REFERENCES = "[{file='my_survey.gpkg', table='my_table', local_path_column='col_with_path', driver_path_column='col_with_ext_url'}]" 
lutraconsulting/mergin-media-sync python3 media_sync_daemon.py
```
