### ISSUE TITLE
Error: Mergin client error on download: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again

### ISSUE THREAD

**Issue by tuankhanh78** [MerginMaps/mergin-media-sync#24]
Hi,

I have an error while trying mergin-media-syn.

docker run -it --name mergin-media-sync -e MERGIN__USERNAME=kdinh -e MERGIN__PASSWORD=xxxxxx -e MERGIN__PROJECT_NAME=kdinh/Soil_Sampling_v2 -e DRIVER=minio -e MINIO__ENDPOINT=minio.url -e MINIO__ACCESS_KEY=Cxxxxxxxx -e MINIO__SECRET_KEY=vTxxxxxxxx -e MINIO__BUCKET=test-mergin -e MINIO__SECURE=1 -e OPERATION_MODE=copy -e 'REFERENCES=[{file='\''Soil_Capture.gpkg'\'', table='\''notes'\'', local_path_column='\''photo'\'', driver_path_column='\''external_url'\''}]' lutraconsulting/mergin-media-sync:latest python3 media_sync_daemon.py
== Starting Mergin Media Sync daemon version 0.2.1 ==
Logging in to Mergin...
Downloading project from Mergin server ...
Error: Mergin client error on download: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Could you tell me where can I assign my merginmaps URL ?
Is there something wrong with the command ?

Thank for your help

Regards

**Comment by PeterPetrik** [comment]
It is `MERGIN__URL`
