### ISSUE TITLE
Error: Mergin client error on download: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by tuankhanh78** [MerginMaps/mergin-media-sync#25]
Hi Peter,
Thank for your help.

I try mergin-media-sync but I get anerror while trying to download.
I create a project media-sync with my account kdinh on app.merginmaps.com.
I get an error while running the following command:
I suppose that the default URL is https://app.merginmaps.com 

docker run -it \
  --name mergin-media-sync \
  -e MERGIN__USERNAME=kdinh \
  -e MERGIN__PASSWORD=strongpasswd \
  -e MERGIN__PROJECT_NAME=kdinh/media-sync \
  -e DRIVER=minio \
  -e MINIO__ENDPOINT="minio.kdinh.fr" \
  -e MINIO__ACCESS_KEY=Cwu48ezKpd9cZaWv4KVb \
  -e MINIO__SECRET_KEY=vTZ-secret-key \
  -e MINIO__BUCKET=test-mergin \
  -e MINIO__SECURE=1 \
  -e OPERATION_MODE=copy \
  -e REFERENCES="[{file='Soil_Capture.gpkg', table='notes', local_path_column='photo', driver_path_column='external_url'}]" \
  lutraconsulting/mergin-media-sync:latest python3 media_sync_daemon.py

![image](https://github.com/MerginMaps/mergin-media-sync/assets/108352380/845a2bc5-478b-4a37-89c9-c6c9603fc3f6)

![image](https://github.com/MerginMaps/mergin-media-sync/assets/108352380/461bfe24-67b6-42a0-93cb-aa8ae82a8e21)

Could you know if something is mismatch ?

Regards

**Comment by tuankhanh78** [comment]
![image](https://github.com/MerginMaps/mergin-media-sync/assets/108352380/acdcd98a-15f1-4f2e-919a-009c0766fccb)


![image](https://github.com/MerginMaps/mergin-media-sync/assets/108352380/3b8651d2-4a9c-4639-b75f-230a932b6a1c)

**Comment by PeterPetrik** [comment]
Hi, Can you please ask questions on Slack merginmaps.com/community/join or support ? Github issues is not a good platform for the chat. Thanks.
